- name: Start pgadmin container
  become: yes
  docker_container:
    name: pgadmin
    image: dpage/pgadmin4:latest
    state: started
    restart_policy: "{{ pgadmin_restart_policy }}"
#    links:
#      - "postgres:postgres"
    published_ports:
      - "{{ pgadmin_port }}:{{ pgadmin_port }}"
    env:
      PGADMIN_DEFAULT_EMAIL: "{{ default_user_email }}"
      PGADMIN_DEFAULT_PASSWORD: "{{ default_user_password }}"
      PGADMIN_LISTEN_PORT: "{{ pgadmin_port }}"
