- name: Start pgadmin container
  become: yes
  become_method: sudo
  docker_container:
    name: pgadmin
    image: fenglc/pgadmin4:latest
    state: started
    restart_policy: always
    links:
      - "postgres:postgres"
    published_ports:
      - "5050:5050"
    env:
      DEFAULT_USER: admin
      DEFAULT_PASSWORD: admin
